BEGIN TRANSACTION;
DROP TABLE IF EXISTS "valores";
CREATE TABLE IF NOT EXISTS "valores" (
	"id"	INTEGER,
	"nombre"	TEXT NOT NULL,
	"valor"	TEXT NOT NULL,
	"fecha_hora"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
